# roles

- name: Configurando o Servidor Bitwarden
  shell:
    cmd: |
      bw config server https://bitwarden.cesarbgoncalves.com.br
  register: config_server

- name: Mostrando resultado da configuração do servidor Bitwarden
  debug:
    var: config_server.stdout_lines
    verbosity: 3

- name: Iniciando o Login
  vars:
    BW_CLIENTID: "{{ BW_CLIENTID }}"
    BW_CLIENTSECRET: "{{ BW_CLIENTSECRET }}"
  shell:
    cmd: |
      echo "Efetuando o login"
      bw login --apikey --quiet

- name: Desbloqueando o cofre
  vars:
    BW_PASSWORD: "{{ BW_PASSWORD }}"
  shell:
    cmd: |
      bw unlock --passwordenv BW_PASSWORD
  register: archive_result

- name: Listando itens
  vars:
    BW_SESSION: "{{ output.stdout | regex_replace('export BW_SESSION=\"(.*?)\"', '\\1') }}"
  shell:
    cmd: |
      bw list items --folderid 29752335-d158-4a48-b036-f206289ce954 | jq -r '.[].id'
