# roles
- name: Configurando o Servidor Bitwarden
  shell:
    cmd: |
      bw config server https://bitwarden.cesarbgoncalves.com.br --quiet

- name: Iniciando o Login
  vars:
    BW_CLIENTID: {{ BW_CLIENTID }}
    BW_CLIENTSECRET: {{ BW_CLIENTSECRET }}
  shell:
    cmd: |
      bw login --apikey

- name: Desbloqueando o cofre
  shell:
    cmd: |
      bw unlock --passwordenv BW_PASSWORD
  register: archive_result

- name: Listando itens
  vars:
    BW_SESSION: "{{ output.stdout | regex_replace('export BW_SESSION=\"(.*?)\"', '\\1') }}"
  shell:
    cmd: |
      bw list items --folderid 29752335-d158-4a48-b036-f206289ce954 | jq -r '.[].id'
