---
# tasks file for create-user

- name: "Adicionando o usuário {{user_name}}"
  user:
    name: "{{user_name}}"
    comment: "{{user_comment}}"
    password: "{{user_password | password_hash('sha512')}}"
    home: "/home/{{user_name}}"
    shell: "/bin/bash"
    ssh_key_file: id_rsa
    update_password: on_create

- name: "Criando arquivo de entrada no Suders para o usuário {{user_name}}"
  file:
    path: "/etc/sudoers.d/{{user_name}}"
    state: touch
    mode: '0600'

- name: "Configurando sudo sem senha para o usuario {{user_name}}"
  lineinfile:
    dest: "/etc/sudoers.d/{{user_name}}"
    line: "{{user_name}}  ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: Usuário criado
  shell: id "{{user_name}}"
  register: new_user_created

- name: Criando Diretorio SSH
  file:
    path: "/home/{{user_name}}/.ssh"
    state: directory
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: '0755'

- name: Copiando arquivos SSH
  copy: 
    src: "{{ item.src }}"
    dest: "{{item.dest}}"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: '0644'
  with_items:
    - { src: 'id_rsa', dest: '/home/{{user_name}}/.ssh/id_rsa'}
    - { src: 'id_rsa.pub', dest: '/home/{{user_name}}/.ssh/id_rsa.pub'}
    - { src: 'prod_rsa', dest: '/home/{{user_name}}/.ssh/prod_rsa'}
    - { src: 'prod_rsa.pub', dest: '/home/{{user_name}}/.ssh/prod_rsa.pub'}

- debug:
    msg: "{{ new_user_created.stdout_lines[0] }}"
...
