- name: Copia arquivos de configuração da AWS
  ansible.builtin.copy:
    src: /home/jenkins/.aws
    dest: /root/.aws
    owner: root
    group: root
    mode: u=rw,g=r,o=r


- name: Enviar arquivo compactado para o S3
  amazon.aws.aws_s3:
    profile: cesar
    bucket: cesarbgoncalves
    object: /backup/pihole/pihole-bkp.{{ansible_date_time.date}}.tar.gz
    src: /tmp/backup-pihole-{{ansible_date_time.date}}.tar.gz
    mode: put
  register: putresult

- debug: msg="{{ putresult.msg }} e a URL do objeto é {{putresult.url}}"
  when: putresult.changed