# - name: Copia arquivos de configuração da AWS
#   ansible.builtin.copy:
#     src: /home/jenkins/.aws/
#     dest: /root/
#     owner: root
#     group: root
#     mode: u=rw,g=r,o=r

- name: Enviar arquivo compactado para o S3
  amazon.aws.aws_s3:
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    bucket: cesarbgoncalves
    object: /backup/pihole/pihole-bkp.{{ansible_date_time.date}}.tar.gz
    src: /tmp/backup-pihole-{{ansible_date_time.date}}.tar.gz
    mode: put
    debug_botocore_endpoint_logs: true
  register: putresult

- debug: msg="{{ putresult.msg }} e a URL do objeto é {{putresult.url}}"
  when: putresult.changed