- hosts: all
  become: true
  name: Fazendo Backup do document.db do Trilium
  community.general.archive:
    path: /home/cesar/k8s_volumes/trilium_home/backup/backup-now.db
    dest: me/cesar/k8s_volumes/trilium_home/backup/backup-now.db.tar.gz
    format: gz
    force_archive: true