---
# rodando em /home/cesar/Documentos/ansible/curso
# Atualizando sistema

- name: Atualizando o Sistema Operacional
  apt:
    name: '*'
    state: latest

- name: Limpando Pacotes desnecessários
  apt:
    autoremove: yes
    purge: yes

- name: Instalação de Pacotes
  apt:
    name: '{{ common_packages_debian }}'
    state: latest

- name: Atualizando o timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/America/Sao_Paulo
    dest: /etc/localtime
    owner: root
    group: root
    state: link

# Copiando um template
- name: Copiando o arquivo de configuracao do VIM
  template:
    src: .vimrc
    dest: /home/{{user_name}}/.vimrc
    force: yes
    owner: "{{user_name}}"
    group: "{{user_name}}"
    mode: "0644"

# # Instalação do NGINX
# - name: Instalação do Nginx
#   yum:
#     name: nginx
#     state: latest
#   notify: Restart NGINX
...