---
- name: "Playbook de configuração inicial do notebook do Cesar"
  hosts: all
  ignore_unreachable: yes
  gather_facts: false
  vars_prompt:
  - name: user_name    
    prompt: "Digite um nome para o usuário"    
    private: no    
    confirm: no    
    salt_size: 7

  - name: user_comment
    prompt: "Digite o nome completo para o usuário"    
    private: no    
    confirm: no    
    salt_size: 7

  - name: user_password
    prompt: "Digite uma senha para o usuário"    
    private: no   
    # encrypt: "md5_crypt" # necessário instalar python-passlib na máquina local    
    confirm: no
    salt_size: 7
  vars:
    user_name: "{{user_name}}"
    user_password: "{{user_password}}"
    user_comment: "{{user_comment}}"
  roles:
    - role: create-user
      become: true
      
    - role: common
      remote_user: cesar
      become: true

    - role: docker
      remote_user: cesar
      become: true
...
